feat: updated helm shared workflow for kubediagram

diff --git a/.github/workflows/helm.yml b/.github/workflows/helm.yml
--- a/.github/workflows/helm.yml
+++ b/.github/workflows/helm.yml
@@ -78,6 +78,16 @@ on:
         type: number
         default: 900
         description: 'The assumed role duration in seconds, if assuming a role. Defaults to 1 hour.'
+      diagram-file-name:
+        required: false
+        type: string
+        description: 'Optional output diagram file name for kube-diagrams'
+      install:
+        required: false
+        type: boolean
+        default: true
+        description: 'Set to false to skip helm install and upgrade step'
+
     secrets:
       AWS_ACCESS_KEY_ID:
         description: 'AWS Access Key ID'
@@ -97,6 +107,7 @@ on:
       set-parameters:
         required: false
         description: 'Overriding the default values using --set flag'
+      
 jobs:
   helm-action:
     runs-on: ubuntu-latest
@@ -157,6 +168,26 @@ jobs:
         run: |
           helm template ${{ inputs.helm-chart-directory }} -f ${{ inputs.values-file-path }}
 
+      - name: Install Graphviz & KubeDiagrams
+        if: ${{ inputs.rollback != true && inputs.uninstall != true }}
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y graphviz
+          pip install git+https://github.com/philippemerle/KubeDiagrams.git
+
+      - name: Generate Helm template and KubeDiagram
+        if: ${{ inputs.rollback != true && inputs.uninstall != true }}
+        run: |
+          helm template ${{ inputs.helm-chart-directory }} --namespace ${{ inputs.namespace }} -f ${{ inputs.values-file-path }} \
+          | kube-diagrams -o "${{ inputs.diagram-file-name }}" -
+
+      - name: Upload Diagram Artifact
+        if: ${{ inputs.rollback != true && inputs.uninstall != true }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: helm-diagram
+          path: ${{ inputs.diagram-file-name }}
+
       - name: helm install and upgrade
         if: ${{ inputs.rollback != true && inputs.uninstall != true }}
         run: |
@@ -168,11 +199,27 @@ jobs:
               --history-max ${{ inputs.history-max }} --atomic --wait --debug --timeout ${{ inputs.timeout }}
           fi
 
-      - name: Rollback Helm Release
+      - name: Helm Rollback
         if: ${{ inputs.rollback == true && inputs.uninstall != true }}
         run: |
-          export HISTORY_COUNT=$(helm history ${{ inputs.release-name }} -n ${{ inputs.namespace }} | head -2 | tail -1 | awk '{print $1}')
-          helm rollback ${{ inputs.release-name }} -n ${{ inputs.namespace }} ${{ inputs.revision }} --debug || ( echo "Valid revision values can be greater than or equal to $HISTORY_COUNT" && exit 1 )
+          echo "⏪ Attempting rollback of release: ${{ inputs.release-name }} to revision ${{ inputs.revision }}"
+
+          # Get revision status (4th column of helm history)
+          REV_STATUS=$(helm history ${{ inputs.release-name }} -n ${{ inputs.namespace }} | awk '$1 == "${{ inputs.revision }}" {print $4}')
+
+          if [ -z "$REV_STATUS" ]; then
+          echo "❌ Revision ${{ inputs.revision }} does not exist."
+          exit 1
+          fi
+
+          if [ "$REV_STATUS" = "failed" ] || [ "$REV_STATUS" = "pending" ]; then
+          echo "⚠️ Revision ${{ inputs.revision }} exists but has status '$REV_STATUS'. Cannot roll back to it."
+          exit 1
+          fi
+
+          echo "✅ Valid revision with status: $REV_STATUS. Proceeding with rollback."
+          helm rollback ${{ inputs.release-name }} -n ${{ inputs.namespace }} ${{ inputs.revision }} --debug
+
 
       - name: Uninstall Helm Release
         if: ${{ inputs.uninstall == true }}
