feat: fixed syntax issue

diff --git a/.github/workflows/terraform_workflow.yml b/.github/workflows/terraform_workflow.yml
--- a/.github/workflows/terraform_workflow.yml
+++ b/.github/workflows/terraform_workflow.yml
@@ -103,7 +103,7 @@ on:
       SERVICE_ACCOUNT:
         required: false
         description: 'The service account to be used'
-        
+
 jobs:
   terraform-workflow:
     runs-on: ubuntu-latest
@@ -243,37 +243,38 @@ jobs:
       #      cd ${{ inputs.working_directory }}
       #      terraform apply -auto-approve
       #     fi
-    - name: terraform apply
-      if: ${{ inputs.destroy != true }}
-      run: |
-        cd ${{ inputs.working_directory }}
+      - name: terraform apply
+        if: ${{ inputs.destroy != true }}
+        run: |
+          cd ${{ inputs.working_directory }}
 
-        if [ -f "errored.tfstate" ]; then
-          echo "Found errored.tfstate, attempting state recovery..."
-          terraform state push errored.tfstate
-          # Optionally move or manage the errored.tfstate file
-          mv errored.tfstate /path/to/backup/location
-        fi
+          # Check for errored state and attempt recovery
+          if [ -f "errored.tfstate" ]; then
+            echo "Found errored.tfstate, attempting state recovery..."
+            terraform state push errored.tfstate
+            mv errored.tfstate /path/to/backup/location # Optionally move or manage the errored.tfstate file
+          fi
 
-        if [ -n "${{ inputs.var_file }}" ]; then
-          terraform apply -var-file="${{ inputs.var_file }}" -auto-approve || {
-            if [ -f "errored.tfstate" ]; then
-              echo "Copying errored.tfstate to S3..."
-              aws s3 cp errored.tfstate s3://${{ inputs.backend_s3_bucket }}/${{ inputs.backend_s3_key }}/errored.tfstate
-            fi
-            exit 1
+          # Run terraform apply with var file if provided, handle errors
+          if [ -n "${{ inputs.var_file }}" ]; then
+            terraform apply -var-file="${{ inputs.var_file }}" -auto-approve || {
+              # Handle error, optionally backup errored state to S3
+              if [ -f "errored.tfstate" ]; then
+                echo "Copying errored.tfstate to S3..."
+                aws s3 cp errored.tfstate s3://${{ inputs.backend_s3_bucket }}/${{ inputs.backend_s3_key }}/errored.tfstate
+              fi
+              exit 1
+            }
+          else
+            terraform apply -auto-approve || {
+              # Handle error, optionally backup errored state to S3
+              if [ -f "errored.tfstate" ]; then
+                echo "Copying errored.tfstate to S3..."
+                aws s3 cp errored.tfstate s3://${{ inputs.backend_s3_bucket }}/${{ inputs.backend_s3_key }}/errored.tfstate
+              fi
+              exit 1
+            }
           }
-        else
-          terraform apply -auto-approve || {
-            if [ -f "errored.tfstate" ]; then
-              echo "Copying errored.tfstate to S3..."
-              aws s3 cp errored.tfstate s3://${{ inputs.backend_s3_bucket }}/${{ inputs.backend_s3_key }}/errored.tfstate
-            fi
-            exit 1
-          }
-        }
-
-
 
       - name: Terraform destroy
         if: ${{ inputs.destroy == true }}
