fix: Update tfdrift.yml

diff --git a/.github/workflows/tfdrift.yml b/.github/workflows/tfdrift.yml
--- a/.github/workflows/tfdrift.yml
+++ b/.github/workflows/tfdrift.yml
@@ -61,169 +61,168 @@ jobs:
 
     steps:
     # Checkout the repository to the GitHub Actions runner
-    - name: Checkout
-      uses: actions/checkout@v3
-
-    - name: Install AWS CLI
-      if: ${{ inputs.provider == 'aws' }}
-      uses: aws-actions/configure-aws-credentials@v3
-      with:
-        aws-access-key-id: ${{ secrets.aws_access_key_id }}
-        aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
-        aws-session-token: ${{ secrets.aws_session_token }}
-        role-to-assume: ${{ secrets.build_role }}
-        aws-region: ${{ inputs.aws_region }}
-        role-duration-seconds: 900
-        role-skip-session-tagging: true
-
-    # Install azure-cli
-    - name: Install Azure CLI
-      if: ${{ inputs.provider == 'azurerm' }}
-      uses: azure/login@v1
-      with:
-        creds: ${{ secrets.AZURE_CREDENTIALS }}
-
-    - name: Set up Terraform
-      uses: hashicorp/setup-terraform@v2
-      with:
-        terraform_version: ${{ inputs.terraform_version }}
-
-    # Run some scripts
-    - name: Run shell commands
-      run: ls -la
-
-    - name: terraform init
-      run: |
-         cd ${{ inputs.working_directory }}
-         terraform init
-
-    # Generates an execution plan for Terraform
-    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
-    - name: Terraform Plan
-      id: tf-plan
-      run: |
-        export exitcode=0
-        cd ${{ inputs.working_directory }}
-        if [ -n "${{ inputs.var_file }}" ]; then
-        terraform plan -detailed-exitcode -no-color -out tfplan --var-file=${{ inputs.var_file }} || export exitcode=$?
-        else
-        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
-        fi
-        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-        if [ $exitcode -eq 1 ]; then
-          echo Terraform Plan Failed!
-          exit 1
-        else
-          exit 0
-        fi
-
-    # Save plan to artifacts
-    - name: Publish Terraform Plan
-      uses: actions/upload-artifact@v3
-      with:
-        name: tfplan
-        path: tfplan
-
-    # Create string output of Terraform Plan
-    - name: Create String Output
-      id: tf-plan-string
-      run: |
-        cd ${{ inputs.working_directory }}
-        TERRAFORM_PLAN=$(terraform show -no-color tfplan)
-        
-        delimiter="$(openssl rand -hex 8)"
-        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
-        echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
-        echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
-        echo "" >> $GITHUB_OUTPUT
-        echo '```terraform' >> $GITHUB_OUTPUT
-        echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
-        echo '```' >> $GITHUB_OUTPUT
-        echo "</details>" >> $GITHUB_OUTPUT
-        echo "${delimiter}" >> $GITHUB_OUTPUT
-        
-    # Publish Terraform Plan as task summary
-    - name: Publish Terraform Plan to Task Summary
-      env:
-        SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
-      run: |
-        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
-
-    # If changes are detected, create a new issue
-    - name: Publish Drift Report
-      if: steps.tf-plan.outputs.exitcode == 2
-      uses: actions/github-script@v6
-      env:
-        SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
-      with:
-          github-token: ${{ secrets.GITHUB }}
-          script: |
-            const body = `${process.env.SUMMARY}`;
-            const title = 'Terraform Configuration Drift Detected';
-            const creator = 'github-actions[bot]'
-          
-            # Look to see if there is an existing drift issue
-            const issues = await github.rest.issues.listForRepo({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              state: 'open',
-              creator: creator,
-              title: title
-            })    
-            if( issues.data.length > 0 ) {
-              // We assume there shouldn't be more than 1 open issue, since we update any issue we find
-              const issue = issues.data[0]
-            if ( issue.body == body ) {
-                console.log('Drift Detected: Found matching issue with duplicate content')
+      - name: Checkout
+        uses: actions/checkout@v3
+    
+      - name: Install AWS CLI
+        if: ${{ inputs.provider == 'aws' }}
+        uses: aws-actions/configure-aws-credentials@v3
+        with:
+          aws-access-key-id: ${{ secrets.aws_access_key_id }}
+          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
+          aws-session-token: ${{ secrets.aws_session_token }}
+          role-to-assume: ${{ secrets.build_role }}
+          aws-region: ${{ inputs.aws_region }}
+          role-duration-seconds: 900
+          role-skip-session-tagging: true
+    
+      # Install azure-cli
+      - name: Install Azure CLI
+        if: ${{ inputs.provider == 'azurerm' }}
+        uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+    
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: ${{ inputs.terraform_version }}
+    
+      # Run some scripts
+      - name: Run shell commands
+        run: ls -la
+    
+      - name: terraform init
+        run: |
+           cd ${{ inputs.working_directory }}
+           terraform init
+    
+      # Generates an execution plan for Terraform
+      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+      - name: Terraform Plan
+        id: tf-plan
+        run: |
+          export exitcode=0
+          cd ${{ inputs.working_directory }}
+          if [ -n "${{ inputs.var_file }}" ]; then
+          terraform plan -detailed-exitcode -no-color -out tfplan --var-file=${{ inputs.var_file }} || export exitcode=$?
+          else
+          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+          fi
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+          if [ $exitcode -eq 1 ]; then
+            echo Terraform Plan Failed!
+            exit 1
+          else
+            exit 0
+          fi
+    
+      # Save plan to artifacts
+      - name: Publish Terraform Plan
+        uses: actions/upload-artifact@v3
+        with:
+          name: tfplan
+          path: tfplan
+    
+      # Create string output of Terraform Plan
+      - name: Create String Output
+        id: tf-plan-string
+        run: |
+          cd ${{ inputs.working_directory }}
+          TERRAFORM_PLAN=$(terraform show -no-color tfplan)
+          delimiter="$(openssl rand -hex 8)"
+          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
+          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
+          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
+          echo "" >> $GITHUB_OUTPUT
+          echo '```terraform' >> $GITHUB_OUTPUT
+          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
+          echo '```' >> $GITHUB_OUTPUT
+          echo "</details>" >> $GITHUB_OUTPUT
+          echo "${delimiter}" >> $GITHUB_OUTPUT
+  
+      # Publish Terraform Plan as task summary
+      - name: Publish Terraform Plan to Task Summary
+        env:
+          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
+        run: |
+          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+    
+      # If changes are detected, create a new issue
+      - name: Publish Drift Report
+        if: steps.tf-plan.outputs.exitcode == 2
+        uses: actions/github-script@v6
+        env:
+          SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
+        with:
+            github-token: ${{ secrets.GITHUB }}
+            script: |
+              const body = `${process.env.SUMMARY}`;
+              const title = 'Terraform Configuration Drift Detected';
+              const creator = 'github-actions[bot]'
+            
+              # Look to see if there is an existing drift issue
+              const issues = await github.rest.issues.listForRepo({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                state: 'open',
+                creator: creator,
+                title: title
+              })    
+              if( issues.data.length > 0 ) {
+                // We assume there shouldn't be more than 1 open issue, since we update any issue we find
+                const issue = issues.data[0]
+              if ( issue.body == body ) {
+                  console.log('Drift Detected: Found matching issue with duplicate content')
+                } else {
+                  console.log('Drift Detected: Found matching issue, updating body')
+                  github.rest.issues.update({
+                    owner: context.repo.owner,
+                    repo: context.repo.repo,
+                    issue_number: issue.number,
+                    body: body
+                  })
+                }
               } else {
-                console.log('Drift Detected: Found matching issue, updating body')
+                console.log('Drift Detected: Creating new issue')
+                github.rest.issues.create({
+                  owner: context.repo.owner,
+                  repo: context.repo.repo,
+                  title: title,
+                  body: body
+               })
+              }
+    
+      # If changes aren't detected, close any open drift issues
+      - name: Publish Drift Report
+        if: steps.tf-plan.outputs.exitcode == 0
+        uses: actions/github-script@v6
+        with:
+            github-token: ${{ secrets.GITHUB }}
+            script: |
+              const title = 'Terraform Configuration Drift Detected';
+              const creator = 'github-actions[bot]'
+            
+              # Look to see if there is an existing drift issue
+              const issues = await github.rest.issues.listForRepo({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                state: 'open',
+                creator: creator,
+                title: title
+              }) 
+              if( issues.data.length > 0 ){
+                const issue = issues.data[0]
                 github.rest.issues.update({
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   issue_number: issue.number,
-                  body: body
+                  state: 'closed'
                 })
               }
-            } else {
-              console.log('Drift Detected: Creating new issue')
-              github.rest.issues.create({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                title: title,
-                body: body
-             })
-            }
-
-    # If changes aren't detected, close any open drift issues
-    - name: Publish Drift Report
-      if: steps.tf-plan.outputs.exitcode == 0
-      uses: actions/github-script@v6
-      with:
-          github-token: ${{ secrets.GITHUB }}
-          script: |
-            const title = 'Terraform Configuration Drift Detected';
-            const creator = 'github-actions[bot]'
-          
-            # Look to see if there is an existing drift issue
-            const issues = await github.rest.issues.listForRepo({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              state: 'open',
-              creator: creator,
-              title: title
-            }) 
-            if( issues.data.length > 0 ) {
-              const issue = issues.data[0]
-              github.rest.issues.update({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                issue_number: issue.number,
-                state: 'closed'
-              })
-            }
-  
-    # Mark the workflow as failed if drift detected
-    - name: Error on Failure
-      if: steps.tf-plan.outputs.exitcode == 2
-      run: exit 1
+    
+      # Mark the workflow as failed if drift detected
+      - name: Error on Failure
+        if: steps.tf-plan.outputs.exitcode == 2
+        run: exit 1
 ...
